### PR TITLE
Update edubots_surveys.Rnw

### PR DESCRIPTION
**Pull request by NoorhanAbbas**
Updated the cited papers

### CODE REVIEW

**Comment by JJ** [comment]
What happened?

**Comment by NoorhanAbbas** [comment]
Hello JJ,
I have added reference in the text....did I break anything?

Thanks,
Noorhan
________________________________

**Comment by JJ** [comment]
Don't worry, you didn't. Only you closed this pull request... Not clear why.

**Comment by NoorhanAbbas** [comment]
Is the text updated or do I need to redo it?
Noorhan
________________________________

**Comment by JJ** [comment]
I'm afraid it's not. I can simply reopen it.

**Review by JJ — APPROVED** [review]
It's fine now. Thanks!

**Pull request merged**
